// preload.js
const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('nexus', {
  runFileOrganizer: () => ipcRenderer.invoke('run-file-organizer'),
  undoLastOrganize: () => ipcRenderer.invoke('undo-last-organize'),
  runDailyDigest:   () => ipcRenderer.invoke('run-daily-digest'),
  runSystemFlush:   () => ipcRenderer.invoke('run-system-flush'),
  runScript:        () => ipcRenderer.invoke('run-script'),
  runBulkRenamer:   (baseName, startNum) => ipcRenderer.invoke('run-bulk-renamer', baseName, startNum),
  runNetChecker:    () => ipcRenderer.invoke('run-net-checker'),
  runBackup:        (source, destination, time, type) => ipcRenderer.invoke('run-backup', source, destination, time, type),
  runAssessment:    (company, email, contact) => ipcRenderer.invoke('run-assessment', company, email, contact),
  runOpenUrls:      (workspace) => ipcRenderer.invoke('run-open-urls', workspace),
  saveWorkspace:    (name, urls) => ipcRenderer.invoke('save-workspace', name, urls),
  deleteWorkspace:  (name) => ipcRenderer.invoke('delete-workspace', name),
  runFeedback:      (data) => ipcRenderer.invoke('run-feedback', data),
  runContact:       (data) => ipcRenderer.invoke('run-contact', data),
  activateLicense: (key) => ipcRenderer.invoke('activate-license', key),
  checkLicense: () => ipcRenderer.invoke('check-license'),
  gdriveAuthUrl:  () => ipcRenderer.invoke('gdrive-auth-url'),
  gdriveExchange: (code) => ipcRenderer.invoke('gdrive-exchange', code),
  gdriveStatus:   () => ipcRenderer.invoke('gdrive-status'),
  gdriveUpload:   (srcDir) => ipcRenderer.invoke('gdrive-upload', srcDir),
  runWebScraper: (config) => ipcRenderer.invoke('run-web-scraper', config),
  runPdfToImage: (config) => ipcRenderer.invoke('run-pdf-to-image', config),
  runImageToPdf: (config) => ipcRenderer.invoke('run-image-to-pdf', config),
  runCompressor: (config) => ipcRenderer.invoke('run-compressor', config),
  runQrCode: (config) => ipcRenderer.invoke('run-qr-code', config),
  runDnsCleaner: () => ipcRenderer.invoke('run-dns-cleaner'),
  runInvoice: (config) => ipcRenderer.invoke('run-invoice', config),
  runFileSplitter: (config) => ipcRenderer.invoke('run-file-splitter', config),
  getExpenses:    () => ipcRenderer.invoke('get-expenses'),
  addExpense:     (entry) => ipcRenderer.invoke('add-expense', entry),
  deleteExpense:  (index) => ipcRenderer.invoke('delete-expense', index),
  exportExpenses: (expenses) => ipcRenderer.invoke('export-expenses', expenses),
  getClipboardHistory:     () => ipcRenderer.invoke('get-clipboard-history'),
  toggleClipboardWatching: (enabled) => ipcRenderer.invoke('toggle-clipboard-watching', enabled),
  copyClipboardEntry:      (id) => ipcRenderer.invoke('copy-clipboard-entry', id),
  pinClipboardEntry:       (id) => ipcRenderer.invoke('pin-clipboard-entry', id),
  deleteClipboardEntry:    (id) => ipcRenderer.invoke('delete-clipboard-entry', id),
  clearClipboardHistory:   () => ipcRenderer.invoke('clear-clipboard-history'),
  onClipboardUpdate: (cb) => {ipcRenderer.removeAllListeners('clipboard-history-updated');
  ipcRenderer.on('clipboard-history-updated', (_, history) => cb(history));
  },
  listInstalledApps: () => ipcRenderer.invoke('list-installed-apps'),
  uninstallApp:      (id) => ipcRenderer.invoke('uninstall-app', id),
  checkForUpdates: () => ipcRenderer.invoke('check-for-updates'),
  downloadUpdate:  () => ipcRenderer.send('download-update'),
  onUpdateAvailable:   (cb) => ipcRenderer.on('update-available',    (_, info) => cb(info)),
  onUpdateNotAvailable:(cb) => ipcRenderer.on('update-not-available', () => cb()),
  onDownloadProgress:  (cb) => ipcRenderer.on('download-progress',   (_, pct)  => cb(pct)),
  onUpdateDownloaded:  (cb) => ipcRenderer.on('update-downloaded',    () => cb()),
  onTrayLaunch:       (cb) => ipcRenderer.on('tray-launch',        (_, id) => cb(id)),
  onTrayCheckUpdates: (cb) => ipcRenderer.on('tray-check-updates', ()      => cb()),

  dropboxAuthUrl:  () => ipcRenderer.invoke('dropbox-auth-url'),
  dropboxExchange: (code) => ipcRenderer.invoke('dropbox-exchange', code),
  dropboxStatus:   () => ipcRenderer.invoke('dropbox-status'),
  dropboxUpload:   (srcDir) => ipcRenderer.invoke('dropbox-upload', srcDir),

  runDuplicateDetector: (folder, action) => ipcRenderer.invoke('run-duplicate-detector', folder, action),
  runSoftwareUpdater: () => ipcRenderer.invoke('run-software-updater'),

  runPasswordGenerator: (config) => ipcRenderer.invoke('run-password-generator', config),
  runStartupManager: (action, name, path, type) => ipcRenderer.invoke('run-startup-manager', action, name, path, type),
}); 
